// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnEk7fYjPZP7m_Z4AfZT_7ugyOHJE5iEI',
    appId: '1:895134771041:web:289fb033506d2f44d14720',
    messagingSenderId: '895134771041',
    projectId: 'coffeeshop-9456f',
    authDomain: 'coffeeshop-9456f.firebaseapp.com',
    storageBucket: 'coffeeshop-9456f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjj3MDbm7re30_9nuLhfAdwqfi2qIGbWY',
    appId: '1:895134771041:android:aa206a82c0190298d14720',
    messagingSenderId: '895134771041',
    projectId: 'coffeeshop-9456f',
    storageBucket: 'coffeeshop-9456f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBoyZk3dtpTYDdN9_u2KzJQFG9lCisj_xc',
    appId: '1:895134771041:ios:c4e75829359d7273d14720',
    messagingSenderId: '895134771041',
    projectId: 'coffeeshop-9456f',
    storageBucket: 'coffeeshop-9456f.firebasestorage.app',
    iosBundleId: 'com.example.projectflutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBoyZk3dtpTYDdN9_u2KzJQFG9lCisj_xc',
    appId: '1:895134771041:ios:c4e75829359d7273d14720',
    messagingSenderId: '895134771041',
    projectId: 'coffeeshop-9456f',
    storageBucket: 'coffeeshop-9456f.firebasestorage.app',
    iosBundleId: 'com.example.projectflutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnEk7fYjPZP7m_Z4AfZT_7ugyOHJE5iEI',
    appId: '1:895134771041:web:ea9bff2d0ab2d028d14720',
    messagingSenderId: '895134771041',
    projectId: 'coffeeshop-9456f',
    authDomain: 'coffeeshop-9456f.firebaseapp.com',
    storageBucket: 'coffeeshop-9456f.firebasestorage.app',
  );
}
